# Generated by Django 3.2.5 on 2021-07-24 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='This is your unique id', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(default='', help_text='Enter your first name', max_length=40)),
                ('Last_Name', models.CharField(default='', help_text='Enter your Last Name', max_length=30)),
                ('EMAil', models.EmailField(help_text='Enter your Email', max_length=70)),
                ('Branch', models.CharField(blank=True, choices=[('ECE', 'ECE'), ('CSE', 'CSE')], default='ECE', help_text='Enter Your Branch', max_length=3)),
                ('phone', models.IntegerField(help_text='Enter your 10 digit phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Recuiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter your company name in full', max_length=100)),
                ('Email', models.EmailField(help_text="enter your point of contact's mail id", max_length=70)),
                ('Phone', models.IntegerField(help_text='enter your 10 digit phone number')),
                ('Job_roles', models.CharField(help_text='Which job roles are you searching for', max_length=100)),
                ('package', models.IntegerField(help_text='enter the package you are offering')),
            ],
        ),
    ]
