# Generated by Django 3.2.5 on 2021-07-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20210724_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='pic',
            field=models.ImageField(default='static/images/play.png', upload_to='static/media/pics'),
        ),
    ]
