# Generated by Django 3.2.5 on 2021-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_candidate_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='pic',
            field=models.ImageField(default='static/images/play.png', upload_to='media/pics'),
        ),
    ]
