# Generated by Django 3.2.5 on 2021-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', help_text='Select your gender', max_length=6),
        ),
    ]
