# Generated by Django 3.2.5 on 2021-07-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_alter_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], help_text='Select your gender', max_length=6),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pic',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
